---
title: "stl_lead_inequity"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
stl_lead <- stl_blood_lead %>% clean_names()
head(stl_lead)
dim(stl_lead)
names(stl_lead)
```

```{r}
stl_lead_prop <- stl_blood_lead %>%
  mutate(white_prop = white / totalPop * 100)


```


```{r}
stl_lead_plot <- ggplot(stl_lead_prop, aes(x = white_prop, y = pctElevated)) + geom_jitter(aes(color = pctElevated)) + scale_color_gradient(low = "blue", high = "orange") +
  theme_minimal() +
  labs(title = "Pct levels vs percentage white",
       caption = "the less percentage of white people in population, the more elevated pct levels",
       x = "white percentage of population",
       y = " elevated pct levels")
stl_lead_plot
ggsave(here::here("figs","stl_lead_plot.png"), height = 5, width = 6)
#the less white people % in population, the more elevated pct levels

stl_lead_hist <- ggplot(stl_lead_prop, aes(x=pctElevated)) + geom_histogram(color = "purple", fill = "green") 
ggsave(here::here("figs","stl_lead_hist.jpg"), height = 5, width = 6)




```



